// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywxybujuxefcjyjiffse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eHlidWp1eGVmY2p5amlmZnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTMzNTIsImV4cCI6MjA3MDcyOTM1Mn0.9nn7er8pX_g541eSWMNQd37twGKL0zmI6Zk2tbLFnIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});